name: akdeniz_cep
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  carousel_slider: ^5.1.1
  firebase_storage: ^13.0.4
  weather: ^3.2.1
  http: ^1.2.2
  intl: ^0.19.0
  material_design_icons_flutter: ^7.0.7296
  image_picker: ^1.2.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.2.5
  google_maps_flutter: ^2.5.0
  label_marker: ^1.0.1
  mobile_scanner: ^5.1.1
  qr_flutter: ^4.1.0
  firebase_messaging: ^16.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
